// LOCALHOST 

### Get all settings GET http://localhost:8080/settings

### Get setting by id GET http://localhost:8080/settings/64695e1266a3ee2325c73840

### Create setting POST http://localhost:8080/settings HTTP/1.1 content-type: application/json
{
    "name": "Setting Name",
    "genre": "Setting Genre",
    "magic": "Magic System if Present",
    "technology": "Technology Level",
    "species": "Intelligent Species",
    "government": "Primary Governments",
    "summary": "Brief Summary of Setting"
}

### PUT setting PUT http://localhost:8080/settings/646962cd7baea69c49399450 HTTP/1.1 content-type: application/json
{
    "name": "Setting Name",
    "genre": "Setting Genre",
    "magic": "Magic System if Present",
    "technology": "Technology Level",
    "species": "Intelligent Species",
    "government": "Primary Governments",
    "summary": "Brief Summary of Setting"
}

// PRODUCTION Deploy 

### Get all settings GET https://worldbuilding-api.onrender.com/settings

### Get setting by id GET https://worldbuilding-api.onrender.com/settings/64695e1266a3ee2325c73840

### Create setting POST https://worldbuilding-api.onrender.com/settings HTTP/1.1 content-type: application/json

{
    "name": "Setting Name",
    "genre": "Setting Genre",
    "magic": "Magic System if Present",
    "technology": "Technology Level",
    "species": "Intelligent Species",
    "government": "Primary Governments",
    "summary": "Brief Summary of Setting"
}

### PUT setting PUT https://worldbuilding-api.onrender.com/settings/646962cd7baea69c49399450 HTTP/1.1 content-type: application/json

{
    "name": "Setting Name",
    "genre": "Setting Genre",
    "magic": "Magic System if Present",
    "technology": "Technology Level",
    "species": "Intelligent Species",
    "government": "Primary Governments",
    "summary": "Brief Summary of Setting"
}